version: '3'

services:
  api:
    build: ./rails-blog-api/
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    ports:
      - 3001:3001
    volumes:
      - ./rails-blog-api:/usr/src/app
      - gem_cache:/bundler_gems
    env_file:
      - ./rails-blog-api/.env
    depends_on:
      - db

  client:
    build: ./react-blog-client/
    command: bash -c "yarn start"
    ports:
      - 3000:3000
    volumes:
      - ./react-blog-client:/usr/src/app
    depends_on:
      - api

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "3306:3306"

  db_test:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - db_test_data:/var/lib/postgresql/data
    ports:
      - "3307:3307"

  redis:
    image: redis 

volumes:
  db_data:
  db_test_data:
  gem_cache:
